function PrimitiveHandler(){this.type="primitive";this.handle=function(){};this.unhandle=function(){}}PrimitiveHandler.prototype.changeEnumValue=changeEnumValue=function(b,c){if(c)for(var a in c){if(c[a]===b)return a}else return b};PrimitiveHandler.prototype.changeByteValue=changeByteValue=function(b,c){if(c)for(var a in c){if(a===b)return c[a]}else return b};PrimitiveHandler.prototype.getType=function(){return this.type};PrimitiveHandler.prototype.parser=function(){return this.handle};
PrimitiveHandler["byte"]={handle:function(b,c){var a=this.buf.readUInt8();this.buf=this.buf.slice(1);this.obj[b]=changeEnumValue(a,c["enum"]);if(void 0==this.obj[b]&&!c.ignore)throw Error("Handler Error - Unknown Value(Name:"+c.name+", Value:"+a+")");void 0!=this.obj[b]&&c.isString&&(this.obj[b]+="");console.log("["+b+":byte] =>",this.obj[b])},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(1),a=changeByteValue(a,c["enum"]);if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+
c.name+", Value:"+a+")");a=0}d.writeUInt8(a);this.bufArray.push(d)}};
PrimitiveHandler["short"]={handle:function(b,c){this.obj[b]=this.buf.readInt16BE();this.buf=this.buf.slice(2);c.isString&&(this.obj[b]+="");console.log("["+b+":short] =>",this.obj[b])},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(2);if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+a+")");a=0}a*=1;if(isNaN(a))throw Error("Unhandle Error - Is NaN(Name:"+c.name+", Value:"+a+")");if(32767<a||-32768>a)throw Error("Unhandle Error - Overflow(Name:"+
c.name+", Value:"+a+")");d.writeInt16BE(a);this.bufArray.push(d)}};
PrimitiveHandler.ushort={handle:function(b,c){this.obj[b]=this.buf.readUInt16BE();this.buf=this.buf.slice(2);c.isString&&(this.obj[b]+="");console.log("["+b+":ushort] =>",this.obj[b])},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(2);if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+a+")");a=0}a*=1;if(isNaN(a))throw Error("Unhandle Error - Is NaN(Name:"+c.name+", Value:"+a+")");if(65535<a||0>a)throw Error("Unhandle Error - Overflow(Name:"+
c.name+", Value:"+a+")");d.writeUInt16BE(a);this.bufArray.push(d)}};
PrimitiveHandler["int"]={handle:function(b,c){this.obj[b]=this.buf.readInt32BE();this.buf=this.buf.slice(4);c.isString&&(this.obj[b]+="");console.log("["+b+":int] =>",this.obj[b])},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(4);if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+a+")");a=0}a*=1;if(isNaN(a))throw Error("Unhandle Error - Is NaN(Name:"+c.name+", Value:"+a+")");if(2147483647<a||-2147483648>a)throw Error("Unhandle Error - Overflow(Name:"+
c.name+", Value:"+a+")");d.writeInt32BE(a);this.bufArray.push(d)}};
PrimitiveHandler.uint={handle:function(b,c){this.obj[b]=this.buf.readUInt32BE();this.buf=this.buf.slice(4);c.isString&&(this.obj[b]+="");console.log("["+b+":uint] =>",this.obj[b])},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(4);if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+a+")");a=0}a*=1;if(isNaN(a))throw Error("Unhandle Error - Is NaN(Name:"+c.name+", Value:"+a+")");if(4294967295<a||0>a)throw Error("Unhandle Error - Overflow(Name:"+
c.name+", Value:"+a+")");d.writeUInt32BE(a);this.bufArray.push(d)}};
PrimitiveHandler.string1={handle:function(b,c){var a=this.buf.readUInt8();if(0===a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+value+")");value=void 0}else value=this.buf.slice(1,a+1).toString();console.log("["+b+":string1] =>",this.obj[b]);this.obj[b]=value;this.buf=this.buf.slice(1+a)},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(1);dataBuf=null;if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+a+
")");a=""}dataBuf=new Buffer(a);d.writeUInt8(dataBuf.length);this.bufArray.push(Buffer.concat([d,dataBuf]))}};
PrimitiveHandler.string2={handle:function(b,c){var a=this.buf.readUInt16BE();if(0===a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+value+")");value=void 0}else value=this.buf.slice(2,a+2).toString();console.log("["+b+":string1] =>",this.obj[b]);this.obj[b]=value;this.buf=this.buf.slice(2+a)},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(2);if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+a+")");a=""}a=
new Buffer(a);d.writeUInt16BE(a.length);this.bufArray.push(Buffer.concat([d,a]))}};
PrimitiveHandler.string4={handle:function(b,c){var a=this.buf.readInt32BE();if(0===a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+value+")");value=void 0}else value=this.buf.slice(4,a+4).toString();console.log("["+b+":string1] =>",this.obj[b]);this.obj[b]=value;this.buf=this.buf.slice(4+a)},unhandle:function(b,c){var a=this.desc[b],d=new Buffer(4);new Buffer(a);if(void 0==a||null==a){if(!c.ignore)throw Error("Unhandle Error - Not Defined(Name:"+c.name+", Value:"+
a+")");a=""}a=new Buffer(a);d.writeUInt32BE(a.length);this.bufArray.push(Buffer.concat([d,a]))}};module.exports=PrimitiveHandler;